<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="admin.aspx.cs" Inherits="bharateeyam.admin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 style="text-align:center;">comment section</h2> <asp:Panel ID="panelgrid" runat="server" GroupingText="delete comments"><asp:GridView ID="Gridreview" runat="server" autogeneratedeletebutton="true" AutoGenerateColumns="false" OnRowDeleting="Gridreview_RowDeleting" >
        <Columns>
            <asp:TemplateField HeaderText="Name">
                <ItemTemplate >
                    <asp:Label ID="lblname" runat="server" Text='<%#Eval("name") %>' />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="comment">
                <ItemTemplate>
                    <%#Eval("comment") %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField Headertext="time">
               <ItemTemplate> <%#Eval("time") %></ItemTemplate>
            </asp:TemplateField>

        </Columns>


    </asp:GridView>
    <asp:Label ID="lblmsg" runat="server"></asp:Label></asp:Panel>
</asp:Content>
